// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// CloudEvent represents a vendor-neutral specification for defining the format
/// of event data.
public struct CloudEvent: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Identifies the event. Producers MUST ensure that source + id is
  /// unique for each distinct event.
  public var id: Swift.String = Swift.String()

  /// Required. Identifies the context in which an event happened.
  /// URI-reference
  public var source: Swift.String = Swift.String()

  /// Required. The version of the CloudEvents specification which the event
  /// uses.
  public var specVersion: Swift.String = Swift.String()

  /// Required. This attribute contains a value describing the type of event
  /// related to the originating occurrence.
  public var type: Swift.String = Swift.String()

  /// Optional. Used for Optional & Extension Attributes
  public var attributes: [Swift.String: CloudEvent.CloudEventAttributeValue] = [:]

  /// The event payload. It should be encoded into a media format which is
  /// specified by the 'datacontenttype' attribute (e.g. application/json), and
  /// adheres to the dataschema format when those respective attributes are
  /// present.
  public var data: OneOf_Data? = nil

  /// Initialize a new instance of `CloudEvent`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CloudEvent().with { $0.id = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case id = "id"
    case source = "source"
    case specVersion = "specVersion"
    case type = "type"
    case attributes = "attributes"
    case binaryData = "binaryData"
    case textData = "textData"
    case protoData = "protoData"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.id = try container.decode(Swift.String.self, forKey: .id)
    self.source = try container.decode(Swift.String.self, forKey: .source)
    self.specVersion = try container.decode(Swift.String.self, forKey: .specVersion)
    self.type = try container.decode(Swift.String.self, forKey: .type)
    self.attributes = try container.decode(
      [Swift.String: CloudEvent.CloudEventAttributeValue].self, forKey: .attributes)

    var data: OneOf_Data? = nil
    let dataCheckAndSet = {
      if data != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath, debugDescription: "Multiple values set for oneof 'data'"
          ))
      }
      data = $0
    }
    if let binaryData = try container.decodeIfPresent(Foundation.Data.self, forKey: .binaryData) {
      try dataCheckAndSet(.binaryData(binaryData))
    }
    if let textData = try container.decodeIfPresent(Swift.String.self, forKey: .textData) {
      try dataCheckAndSet(.textData(textData))
    }
    if let protoData = try container.decodeIfPresent(GoogleCloudWKT.`Any`?.self, forKey: .protoData)
    {
      try dataCheckAndSet(.protoData(protoData))
    }
    self.data = data
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.id, forKey: .id)
    try container.encode(self.source, forKey: .source)
    try container.encode(self.specVersion, forKey: .specVersion)
    try container.encode(self.type, forKey: .type)
    try container.encode(self.attributes, forKey: .attributes)

    if let choice = self.data {
      switch choice {
      case .binaryData(let value):
        try container.encode(value, forKey: .binaryData)
      case .textData(let value):
        try container.encode(value, forKey: .textData)
      case .protoData(let value):
        try container.encode(value, forKey: .protoData)
      }
    }
  }

  /// The following abstract data types are available for use in attributes.
  public struct CloudEventAttributeValue: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The value of the attribute.
    public var attr: OneOf_Attr? = nil

    /// Initialize a new instance of `CloudEventAttributeValue`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CloudEventAttributeValue().with { $0.ceBoolean = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case ceBoolean = "ceBoolean"
      case ceInteger = "ceInteger"
      case ceString = "ceString"
      case ceBytes = "ceBytes"
      case ceUri = "ceUri"
      case ceUriRef = "ceUriRef"
      case ceTimestamp = "ceTimestamp"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var attr: OneOf_Attr? = nil
      let attrCheckAndSet = {
        if attr != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'attr'"))
        }
        attr = $0
      }
      if let ceBoolean = try container.decodeIfPresent(Swift.Bool.self, forKey: .ceBoolean) {
        try attrCheckAndSet(.ceBoolean(ceBoolean))
      }
      if let ceInteger = try container.decodeIfPresent(Swift.Int32.self, forKey: .ceInteger) {
        try attrCheckAndSet(.ceInteger(ceInteger))
      }
      if let ceString = try container.decodeIfPresent(Swift.String.self, forKey: .ceString) {
        try attrCheckAndSet(.ceString(ceString))
      }
      if let ceBytes = try container.decodeIfPresent(Foundation.Data.self, forKey: .ceBytes) {
        try attrCheckAndSet(.ceBytes(ceBytes))
      }
      if let ceUri = try container.decodeIfPresent(Swift.String.self, forKey: .ceUri) {
        try attrCheckAndSet(.ceUri(ceUri))
      }
      if let ceUriRef = try container.decodeIfPresent(Swift.String.self, forKey: .ceUriRef) {
        try attrCheckAndSet(.ceUriRef(ceUriRef))
      }
      if let ceTimestamp = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp?.self, forKey: .ceTimestamp)
      {
        try attrCheckAndSet(.ceTimestamp(ceTimestamp))
      }
      self.attr = attr
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.attr {
        switch choice {
        case .ceBoolean(let value):
          try container.encode(value, forKey: .ceBoolean)
        case .ceInteger(let value):
          try container.encode(value, forKey: .ceInteger)
        case .ceString(let value):
          try container.encode(value, forKey: .ceString)
        case .ceBytes(let value):
          try container.encode(value, forKey: .ceBytes)
        case .ceUri(let value):
          try container.encode(value, forKey: .ceUri)
        case .ceUriRef(let value):
          try container.encode(value, forKey: .ceUriRef)
        case .ceTimestamp(let value):
          try container.encode(value, forKey: .ceTimestamp)
        }
      }
    }

    /// The value of the attribute.
    public enum OneOf_Attr: Codable, Equatable, Sendable {
      /// Boolean value.
      case ceBoolean(Swift.Bool)
      /// Integer value.
      case ceInteger(Swift.Int32)
      /// String value.
      case ceString(Swift.String)
      /// Bytes value.
      case ceBytes(Foundation.Data)
      /// URI value.
      case ceUri(Swift.String)
      /// URI-reference value.
      case ceUriRef(Swift.String)
      /// Timestamp value.
      indirect case ceTimestamp(GoogleCloudWKT.Timestamp?)
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.eventarc.publishing.v1.CloudEvent.CloudEventAttributeValue"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The event payload. It should be encoded into a media format which is
  /// specified by the 'datacontenttype' attribute (e.g. application/json), and
  /// adheres to the dataschema format when those respective attributes are
  /// present.
  public enum OneOf_Data: Codable, Equatable, Sendable {
    /// Optional. Binary data.
    case binaryData(Foundation.Data)
    /// Optional. Text data.
    case textData(Swift.String)
    /// Optional. Proto data.
    ///
    /// NOTE: The `protoData` field only functions as expected when the payload
    /// is specifically a `CloudEvent` message type, and can't be used for
    /// arbitrary protocol buffer messages. For any other protocol buffer type,
    /// you must serialize your proto message into bytes, and use the
    /// `binaryData` field instead.
    indirect case protoData(GoogleCloudWKT.`Any`?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.publishing.v1.CloudEvent"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
