// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// The request message for the PublishChannelConnectionEvents method.
public struct PublishChannelConnectionEventsRequest: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The channel_connection that the events are published from. For example:
  /// `projects/{partner_project_id}/locations/{location}/channelConnections/{channel_connection_id}`.
  public var channelConnection: Swift.String = Swift.String()

  /// The CloudEvents v1.0 events to publish. No other types are allowed.
  /// If this field is set, then the `text_events` fields must not be set.
  public var events: [GoogleWKT.WKTAny] = []

  /// The text representation of events to publish.
  /// CloudEvent v1.0 in JSON format is the only allowed type. Refer to
  /// https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md
  /// for specification.
  /// If this field is set, then the `events` fields must not be set.
  public var textEvents: [Swift.String] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PublishChannelConnectionEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PublishChannelConnectionEventsRequest().with { $0.channelConnection = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let channelConnection = CodingKeys(stringValue: "channelConnection")
    static let events = CodingKeys(stringValue: "events")
    static let textEvents = CodingKeys(stringValue: "textEvents")

    static let _knownKeys: Set<Swift.String> = [
      "channelConnection",
      "events",
      "textEvents",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .channelConnection) {
      self.channelConnection = value
    }
    if let value = try container.decodeIfPresent([GoogleWKT.WKTAny].self, forKey: .events) {
      self.events = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .textEvents) {
      self.textEvents = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.channelConnection, forKey: .channelConnection)
    try container.encode(self.events, forKey: .events)
    try container.encode(self.textEvents, forKey: .textEvents)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return
      "type.googleapis.com/google.cloud.eventarc.publishing.v1.PublishChannelConnectionEventsRequest"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
