// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message for the PublishEvents method.
public struct PublishEventsRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// The full name of the channel to publish to. For example:
  /// `projects/{project}/locations/{location}/channels/{channel-id}`.
  public var channel: Swift.String = Swift.String()

  /// The CloudEvents v1.0 events to publish. No other types are allowed.
  /// If this field is set, then the `text_events` fields must not be set.
  public var events: [GoogleCloudWkt.`Any`] = []

  /// The text representation of events to publish.
  /// CloudEvent v1.0 in JSON format is the only allowed type. Refer to
  /// https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md
  /// for specification.
  /// If this field is set, then the `events` fields must not be set.
  public var textEvents: [Swift.String] = []

  /// Initialize a new instance of `PublishEventsRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PublishEventsRequest().with { $0.channel = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.publishing.v1.PublishEventsRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
