// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWKT
import GoogleCloudGax

/// Eventarc processes events generated by an event provider and delivers them to
/// a subscriber.
///
/// An event provider is a software-as-a-service (SaaS) system or
/// product that can generate and deliver events through Eventarc.
///
/// A third-party event provider is an event provider from outside of Google.
///
/// A partner is a third-party event provider that is integrated with Eventarc.
///
/// A subscriber is a Google Cloud customer interested in receiving events.
///
/// Channel is a first-class Eventarc resource that is created and managed
/// by the subscriber in their Google Cloud project. A Channel represents a
/// subscriber's intent to receive events from an event provider. A Channel is
/// associated with exactly one event provider.
///
/// ChannelConnection is a first-class Eventarc resource that
/// is created and managed by the partner in their Google Cloud project. A
/// ChannelConnection represents a connection between a partner and a
/// subscriber's Channel. A ChannelConnection has a one-to-one mapping with a
/// Channel.
///
/// Bus is a first-class Eventarc resource that is created and managed in a
/// Google Cloud project. A Bus provides a discoverable endpoint for events and
/// is a router that receives all events published by event providers and
/// delivers them to zero or more subscribers.
///
/// Publisher allows an event provider to publish events to Eventarc.
///
/// @Snippet(path: "PublisherQuickstart")
public final class PublisherClient: Clients.PublisherProtocol, Sendable {
  let inner: any Clients.PublisherStub

  /// Creates a new `PublisherClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.PublisherStub = try Clients.PublisherTransport(options)
    inner = Clients.PublisherRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.PublisherLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Publish events to a ChannelConnection in a partner's project.
  ///
  /// @Snippet(path: "Publisher_PublishChannelConnectionEvents")
  public func publishChannelConnectionEvents(
    request: PublishChannelConnectionEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEventarcPublishingV1.PublishChannelConnectionEventsResponse {
    try await self.inner.publishChannelConnectionEvents(request: request, options: options)
  }

  /// Publish events to a subscriber's channel.
  ///
  /// @Snippet(path: "Publisher_PublishEvents")
  public func publishEvents(
    request: PublishEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEventarcPublishingV1.PublishEventsResponse {
    try await self.inner.publishEvents(request: request, options: options)
  }

  /// Publish events to a message bus.
  ///
  /// @Snippet(path: "Publisher_Publish")
  public func publish(
    request: PublishRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEventarcPublishingV1.PublishResponse {
    try await self.inner.publish(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `PublisherClient`.
  ///
  /// To mock `PublisherClient` change your functions to receive
  /// `some PublisherProtocol` or `any PublisherProtocol`
  /// and pass a mock implementation in your tests.
  public protocol PublisherProtocol {
    /// See `PublisherClient.publishChannelConnectionEvents`.
    func publishChannelConnectionEvents(request: PublishChannelConnectionEventsRequest) async throws
      -> GoogleCloudEventarcPublishingV1.PublishChannelConnectionEventsResponse

    /// See `PublisherClient.publishEvents`.
    func publishEvents(request: PublishEventsRequest) async throws
      -> GoogleCloudEventarcPublishingV1.PublishEventsResponse

    /// See `PublisherClient.publish`.
    func publish(request: PublishRequest) async throws
      -> GoogleCloudEventarcPublishingV1.PublishResponse

    /// See `PublisherClient.publishChannelConnectionEvents`.
    func publishChannelConnectionEvents(
      request: PublishChannelConnectionEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcPublishingV1.PublishChannelConnectionEventsResponse

    /// See `PublisherClient.publishEvents`.
    func publishEvents(
      request: PublishEventsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcPublishingV1.PublishEventsResponse

    /// See `PublisherClient.publish`.
    func publish(
      request: PublishRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEventarcPublishingV1.PublishResponse
  }
}

// Default implementations
extension Clients.PublisherProtocol {
  public func publishChannelConnectionEvents(request: PublishChannelConnectionEventsRequest)
    async throws -> GoogleCloudEventarcPublishingV1.PublishChannelConnectionEventsResponse
  {
    try await self.publishChannelConnectionEvents(request: request, options: .init())
  }

  public func publishChannelConnectionEvents(
    request: PublishChannelConnectionEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEventarcPublishingV1.PublishChannelConnectionEventsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func publishEvents(request: PublishEventsRequest) async throws
    -> GoogleCloudEventarcPublishingV1.PublishEventsResponse
  {
    try await self.publishEvents(request: request, options: .init())
  }

  public func publishEvents(
    request: PublishEventsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEventarcPublishingV1.PublishEventsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func publish(request: PublishRequest) async throws
    -> GoogleCloudEventarcPublishingV1.PublishResponse
  {
    try await self.publish(request: request, options: .init())
  }

  public func publish(
    request: PublishRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEventarcPublishingV1.PublishResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
