// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// The request message for the Publish method.
public struct PublishRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The full name of the message bus to publish events to. Format:
  /// `projects/{project}/locations/{location}/messageBuses/{messageBus}`.
  public var messageBus: Swift.String = Swift.String()

  public var format: OneOf_Format? = nil

  /// Initialize a new instance of `PublishRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PublishRequest().with { $0.messageBus = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case messageBus = "messageBus"
    case protoMessage = "protoMessage"
    case jsonMessage = "jsonMessage"
    case avroMessage = "avroMessage"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.messageBus = try container.decode(Swift.String.self, forKey: .messageBus)

    var format: OneOf_Format? = nil
    let formatCheckAndSet = {
      if format != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'format'"))
      }
      format = $0
    }
    if let protoMessage = try container.decodeIfPresent(CloudEvent?.self, forKey: .protoMessage) {
      try formatCheckAndSet(.protoMessage(protoMessage))
    }
    if let jsonMessage = try container.decodeIfPresent(Swift.String.self, forKey: .jsonMessage) {
      try formatCheckAndSet(.jsonMessage(jsonMessage))
    }
    if let avroMessage = try container.decodeIfPresent(Foundation.Data.self, forKey: .avroMessage) {
      try formatCheckAndSet(.avroMessage(avroMessage))
    }
    self.format = format
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.messageBus, forKey: .messageBus)

    if let choice = self.format {
      switch choice {
      case .protoMessage(let value):
        try container.encode(value, forKey: .protoMessage)
      case .jsonMessage(let value):
        try container.encode(value, forKey: .jsonMessage)
      case .avroMessage(let value):
        try container.encode(value, forKey: .avroMessage)
      }
    }
  }

  public enum OneOf_Format: Codable, Equatable, Sendable {
    /// The Protobuf format of the CloudEvent being published. Specification can
    /// be found here:
    /// https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/protobuf-format.md
    indirect case protoMessage(CloudEvent?)
    /// The JSON format of the CloudEvent being published. Specification can be
    /// found here:
    /// https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/json-format.md
    case jsonMessage(Swift.String)
    /// The Avro format of the CloudEvent being published. Specification can
    /// be found here:
    /// https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/formats/avro-format.md
    case avroMessage(Foundation.Data)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.eventarc.publishing.v1.PublishRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
